# Generated by Django 4.0.8 on 2022-11-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('student_name', models.CharField(default='', max_length=30)),
                ('father_name', models.CharField(default='', max_length=30)),
                ('stud_class', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='husnain_app.teacher')),
            ],
        ),
    ]
