# Generated by Django 4.1.2 on 2022-10-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('husnain_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_class',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
